//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secs4Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Secs4Net.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Device Id.
        /// </summary>
        internal static string S9F1 {
            get {
                return ResourceManager.GetString("S9F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Too Long.
        /// </summary>
        internal static string S9F11 {
            get {
                return ResourceManager.GetString("S9F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation Timeout.
        /// </summary>
        internal static string S9F13 {
            get {
                return ResourceManager.GetString("S9F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Stream Type.
        /// </summary>
        internal static string S9F3 {
            get {
                return ResourceManager.GetString("S9F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Function Type.
        /// </summary>
        internal static string S9F5 {
            get {
                return ResourceManager.GetString("S9F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Data.
        /// </summary>
        internal static string S9F7 {
            get {
                return ResourceManager.GetString("S9F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Timer Timeout.
        /// </summary>
        internal static string S9F9 {
            get {
                return ResourceManager.GetString("S9F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S9Fy message reply..
        /// </summary>
        internal static string S9Fy {
            get {
                return ResourceManager.GetString("S9Fy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream number must be less than 127.
        /// </summary>
        internal static string SecsMessageStreamNumberMustLessThan127 {
            get {
                return ResourceManager.GetString("SecsMessageStreamNumberMustLessThan127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment is not online mode.
        /// </summary>
        internal static string SxF0 {
            get {
                return ResourceManager.GetString("SxF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T3 Timeout!.
        /// </summary>
        internal static string T3Timeout {
            get {
                return ResourceManager.GetString("T3Timeout", resourceCulture);
            }
        }
    }
}
